GROOVY_AS = 'as'
GROOVY_ASSERT = 'assert'
GROOVY_BREAK = 'break'
GROOVY_CASE = 'case'
GROOVY_CATCH = 'catch'
GROOVY_CLASS = 'class'
GROOVY_CONST = 'const'
GROOVY_CONTINUE = 'continue'
GROOVY_DEF = 'def'
GROOVY_DEFAULT = 'default'
GROOVY_DO = 'do'
GROOVY_ELSE = 'else'
GROOVY_ENUM = 'enum'
GROOVY_EXTENDS = 'extends'
GROOVY_FALSE = 'false'
GROOVY_FINALLY = 'finally'
GROOVY_FOR = 'for'
GROOVY_GOTO = 'goto'
GROOVY_IF = 'if'
GROOVY_IMPLEMENTS = 'implements'
GROOVY_IMPORT = 'import'
GROOVY_IN = 'in'
GROOVY_INSTANCEOF = 'instanceof'
GROOVY_INTERFACE = 'interface'
GROOVY_NEW = 'new'
GROOVY_NULL = 'null'
GROOVY_PACKAGE = 'package'
GROOVY_RETURN = 'return'
GROOVY_SUPER = 'super'
GROOVY_SWITCH = 'switch'
GROOVY_THIS = 'this'
GROOVY_THROW = 'throw'
GROOVY_THROWS = 'throws'
GROOVY_TRAIT = 'trait'
GROOVY_TRUE = 'true'
GROOVY_TRY = 'try'
GROOVY_VAR = 'var'
GROOVY_WHILE = 'while'

GROOVY_KEYWORDS = [GROOVY_AS, GROOVY_ASSERT, GROOVY_BREAK, GROOVY_CASE, GROOVY_CATCH, GROOVY_CLASS, GROOVY_CONST,
                   GROOVY_CONTINUE, GROOVY_DEF, GROOVY_DEFAULT, GROOVY_DO, GROOVY_ELSE, GROOVY_ENUM, GROOVY_EXTENDS,
                   GROOVY_FALSE, GROOVY_FINALLY, GROOVY_FOR, GROOVY_GOTO, GROOVY_IF, GROOVY_IMPLEMENTS, GROOVY_IMPORT,
                   GROOVY_IN, GROOVY_INSTANCEOF, GROOVY_INTERFACE, GROOVY_NEW, GROOVY_NULL, GROOVY_PACKAGE,
                   GROOVY_RETURN, GROOVY_SUPER, GROOVY_SWITCH, GROOVY_THIS, GROOVY_THROW, GROOVY_THROWS, GROOVY_TRAIT,
                   GROOVY_TRUE, GROOVY_TRY, GROOVY_VAR, GROOVY_WHILE,
                   ]

GROOVY_COMMA = ','
GROOVY_COLON = ':'
GROOVY_DOTCOMMA = ';'
GROOVY_DOT = '.'
GROOVY_LEFT_BRACKET = '['
GROOVY_RIGHT_BRACKET = ']'
GROOVY_LEFT_BRACE = '{'
GROOVY_RIGHT_BRACE = '}'
GROOVY_LEFT_PARENTHESES = '('
GROOVY_RIGHT_PARENTHESES = ')'

GROOVY_PUNCTUATION = [GROOVY_COMMA, GROOVY_COLON, GROOVY_DOTCOMMA, GROOVY_DOT, GROOVY_LEFT_BRACKET,
                      GROOVY_RIGHT_BRACKET, GROOVY_LEFT_BRACE, GROOVY_RIGHT_BRACE, GROOVY_LEFT_PARENTHESES,
                      GROOVY_RIGHT_PARENTHESES,
                      ]

GROOVY_QUOTE = ['\"', '\'']
GROOVY_WHITESPACE = [' ', '\t', '\b', '\n', '\r']
